### ISSUE TITLE
Possible Things To Do

### ISSUE THREAD

**Issue by jimmybolt** [TriHardStudios/TSA-Software-2018#23]
Camera free pan during animation - DONE should beutify interface
Ability to 'jump' to key frames 
Get meshes working - NO
Get lighting working -DONE
Get Obj importing working - DONE should make it handle more verticies - DONE
Add ability to export animation to a video - DONE Not yet implemented in this UI

**Comment by jimmybolt** [comment]
Feel free to add anything

**Comment by NibrocCode** [comment]
I’ll work on duplication of shapes and lighting.

**Comment by jkmosa01** [comment]
Frame counter

**Comment by TriHardStudios** [comment]
Better UI.
Move the load save box to be pretty inside of the button and make it look good.
Make the tutorial popups, not popups.
Add built-in documentation
Fix delete save 
Less scrolling 
Make save engine more redundant
Make readme sexy 
Cry as I realize that we can't possibly get all of these done.

**Comment by TriHardStudios** [comment]
Most of the stuff that I set out to fix is pretty much done
